spring:
  application:
    name: bookmark
#  profiles:
#    active: local
#  cloud:
#    config:
#      name: bookmark
#    bus:
#      enabled: true
#  config:
#    import: "optional:configserver:http://localhost:8888"
  datasource:
    url: jdbc:mariadb://192.168.3.8:3306/test
    username: test
    password:
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    show_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000

  rabbitmq:
    host: 192.168.3.8
    port: 5672
    username: admin
    password: admin

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"
