server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/User/IdeaProjects/config-repo
          default-label: master
          searchPaths: prod, local
