server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native # git
  rabbitmq:
    host: 192.168.3.8
    port: 5672
    username: admin
    password: admin
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/config-repo
#      server:
#        git:
#          uri: file:///C://Users//User//IdeaProjects//config-repo
#          default-label: master
#          searchPaths: prod, local

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    refresh:
      enabled: true